### ISSUE TITLE
취업 메인 페이지를 제작한다. 

### ISSUE THREAD

**Issue by dorrion** [dorrion/Psychology-Brochure#13]
## Description

취업 메인 페이지를 제작한다. 

- 취업 현황
- 취업 인터뷰

## Todo

- [ ] 취업 현황 클릭 시 취업 관련 정보로 라우팅
- [ ] 취업 인터뷰 카드 컴포넌트 구현
- [ ] 취업 인터뷰 카드 클릭 시 해당 인터뷰 페이지로 라우팅
