### ISSUE TITLE
심리학과에서 메일 쓰기 페이지를 제작한다.

### ISSUE THREAD

**Issue by dorrion** [dorrion/Psychology-Brochure#9]
## Description

심리학과에서 메일 쓰기 페이지를 제작한다.

## Todo

- [ ] 공식적인 메일 작성 요소 정렬
- [ ] 메일 작성 컨셉쪽 작성
- [ ] 반응형 및 다크모드 작업

## ETC
-
